export const jobSkillCategories = [
  { code: "01", displayName: "사업관리" },
  { code: "02", displayName: "경영·회계·사무" },
  { code: "03", displayName: "금융·보험" },
  { code: "04", displayName: "교육·자연·사회과학" },
  { code: "05", displayName: "법률·경찰·소방·교도·국방" },
  { code: "06", displayName: "보건·의료" },
  { code: "07", displayName: "사회복지·종교" },
  { code: "08", displayName: "문화·예술·디자인·방송" },
  { code: "09", displayName: "운전·운송" },
  { code: "10", displayName: "영업판매" },
  { code: "11", displayName: "경비·청소" },
  { code: "12", displayName: "이용·숙박·여행·오락·스포츠" },
  { code: "13", displayName: "음식서비스" },
  { code: "14", displayName: "건설" },
  { code: "15", displayName: "기계" },
  { code: "16", displayName: "재료" },
  { code: "17", displayName: "화학·바이오" },
  { code: "18", displayName: "섬유·의복" },
  { code: "19", displayName: "전기·전자" },
  { code: "20", displayName: "정보통신" },
  { code: "21", displayName: "식품가공" },
  { code: "22", displayName: "인쇄·목재·가구·공예" },
  { code: "23", displayName: "환경·에너지·안전" },
  { code: "24", displayName: "농림어업" },
];

export const govEduCategories = [];
